name = "environment"
uuid = "5eeecf99-d45e-4d73-a6a5-5e7f667d3dde"
authors = ["johnryantaylor <johnryantaylor@gmail.com>"]
version = "0.1.0"

[deps]
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
Oceananigans = "9e8cae18-63c1-5223-a75c-80ca9d6e9a09"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
